version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      JVM_OPTS: "-Xmx5G"
    restart: unless-stopped
    volumes:
      - /home/manu/minecraft_servers/server_andreu/:/data
    networks:
      rcon_network:


  mc_console:
    image: mc-console:latest
    ports:
      - "8123:80"
    environment:   
      HOST_MC: "172.22.0.2"
    volumes:
      - /home/manu/minecraft_servers/server_andreu/:/data
    networks:
      rcon_network:
    command:
      "python3 app.py"

networks:
  rcon_network:
