import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sidebar from "@/components/sidebar";
import HeadServer from "@/components/server/head";
import { notFound } from "next/navigation";
import { getServers } from "@/lib/get_server_data"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
    children, params,
}: Readonly<{
    children: React.ReactNode; params: { id: string }
}>) {
    const serversList = await getServers();
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" media="all" />
            </head>
            <body className={inter.className + " bg-[#2E4F4F]"}>
                <div className="">
                    <Sidebar serversList={serversList}></Sidebar>
                    {children}
                </div>
            </body>
        </html>
    );
}
